import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
async function app() { let source=''; try { source=await readFile(new URL('../public/app.js',import.meta.url),'utf8'); } catch {} return import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')); }
test('state labels never imply an unconfigured provider is live',async()=>{const m=await app();assert.equal(typeof m.stateLabel,'function');assert.equal(m.stateLabel(null),'Connecting');assert.equal(m.stateLabel({provider:{ready:false}}),'Provider offline');assert.equal(m.stateLabel({provider:{ready:true},running:true}),'Working');assert.equal(m.stateLabel({provider:{ready:true},running:false}),'Ready');});
test('six meeting positions are distinct and office motion stays on the floor',async()=>{const m=await app();assert.equal(typeof m.flyPosition,'function');const points=Array.from({length:6},(_,i)=>m.flyPosition(i,10,true));assert.equal(new Set(points.map(p=>JSON.stringify(p))).size,6);for(let i=0;i<6;i++)for(let t=0;t<100;t+=5){const p=m.flyPosition(i,t,false);assert.equal(p.y,0);assert.ok(Math.hypot(p.x,p.z)<10);assert.ok(Number.isFinite(p.heading));}assert.deepEqual(m.flyPosition(2,0,true),m.flyPosition(2,40,true));assert.notDeepEqual(m.flyPosition(2,0,false),m.flyPosition(2,40,false));});
test('source URLs block executable and malformed protocols',async()=>{const m=await app();assert.equal(typeof m.safeURL,'function');for(const url of ['javascript:alert(1)','data:text/html,test','bad'])assert.equal(m.safeURL(url),'#');assert.equal(m.safeURL('https://example.com/paper'),'https://example.com/paper');});
test('visitor client subscribes to persisted meeting events',async()=>{const source=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(source,/EventSource/);assert.match(source,/\/api\/events/);});
test('escapes untrusted API text for HTML',async()=>{const m=await app();assert.equal(typeof m.escapeHTML,'function');assert.equal(m.escapeHTML('<img onerror="x"> & \'a\''),'&lt;img onerror=&quot;x&quot;&gt; &amp; &#39;a&#39;');});
