import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
async function app() { let source=''; try { source=await readFile(new URL('../public/app.js',import.meta.url),'utf8'); } catch {} return import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')); }
test('state labels describe the local Hermes worker without exposing provider configuration',async()=>{const m=await app();assert.equal(typeof m.stateLabel,'function');assert.equal(m.stateLabel(null),'Connecting');assert.equal(m.stateLabel({provider:{ready:false}}),'Hermes local worker');assert.equal(m.stateLabel({provider:{ready:true},running:true}),'Hermes working');assert.equal(m.stateLabel({provider:{ready:true},running:false}),'Hermes local worker');});
test('six meeting positions are distinct and office motion stays on the floor',async()=>{const m=await app();assert.equal(typeof m.flyPosition,'function');const points=Array.from({length:6},(_,i)=>m.flyPosition(i,10,true));assert.equal(new Set(points.map(p=>JSON.stringify(p))).size,6);for(let i=0;i<6;i++)for(let t=0;t<100;t+=5){const p=m.flyPosition(i,t,false);assert.equal(p.y,0);assert.ok(Math.hypot(p.x,p.z)<10);assert.ok(Number.isFinite(p.heading));}assert.deepEqual(m.flyPosition(2,0,true),m.flyPosition(2,40,true));assert.notDeepEqual(m.flyPosition(2,0,false),m.flyPosition(2,40,false));});
test('source URLs block executable and malformed protocols',async()=>{const m=await app();assert.equal(typeof m.safeURL,'function');for(const url of ['javascript:alert(1)','data:text/html,test','bad'])assert.equal(m.safeURL(url),'#');assert.equal(m.safeURL('https://example.com/paper'),'https://example.com/paper');});
test('visitor client subscribes to persisted meeting events',async()=>{const source=await readFile(new URL('../public/app.js',import.meta.url),'utf8');assert.match(source,/EventSource/);assert.match(source,/\/api\/events/);});
test('header links to the official Fruit Fly company X profile',async()=>{const source=await readFile(new URL('../public/index.html',import.meta.url),'utf8');assert.match(source,/href="https:\/\/x\.com\/FLYCORPBNB"/);assert.match(source,/target="_blank" rel="noopener noreferrer" aria-label="Fruit Fly company on Twitter"/);});
test('website uses the Fruit Fly company name',async()=>{const index=await readFile(new URL('../public/index.html',import.meta.url),'utf8');const appSource=await readFile(new URL('../public/app.js',import.meta.url),'utf8');const specimen=await readFile(new URL('../public/specimen.html',import.meta.url),'utf8');assert.ok(index.includes('<title>Fruit Fly company</title>'));assert.ok(index.includes('FRUIT FLY<br>COMPANY'));assert.ok(appSource.includes("fillText('FRUIT FLY COMPANY'"));assert.ok(specimen.includes('Return to Fruit Fly company'));for(const source of [index,appSource,specimen])assert.doesNotMatch(source,/\bFly Company\b/);});
test('main page omits the token contract-address container',async()=>{const index=await readFile(new URL('../public/index.html',import.meta.url),'utf8');const appSource=await readFile(new URL('../public/app.js',import.meta.url),'utf8');const styles=await readFile(new URL('../public/style.css',import.meta.url),'utf8');for(const source of [index,appSource,styles]){assert.doesNotMatch(source,/token-strip|token-address|copy-token|token-copy/);}assert.doesNotMatch(index,/0xfbfe65839e0bb915e78b35e927036f81a25c7777/i);});
test('office panel omits the worker status card and circular intro mark',async()=>{const source=await readFile(new URL('../public/app.js',import.meta.url),'utf8');const officeBlock=source.match(/if\(tab==='office'\)(.*?);\n    if\(tab==='research'/s)?.[1]||'';assert.doesNotMatch(officeBlock,/Hermes local worker/);assert.doesNotMatch(officeBlock,/intro-icon|◎/);});
test('escapes untrusted API text for HTML',async()=>{const m=await app();assert.equal(typeof m.escapeHTML,'function');assert.equal(m.escapeHTML('<img onerror="x"> & \'a\''),'&lt;img onerror=&quot;x&quot;&gt; &amp; &#39;a&#39;');});
